{
    'name': 'Motorcycle Financing',
    'summary': 'Streamlines the loan application process for dealerships.',
    'description': 'This module helps K\'awiil Motors track and manage motorcycle loan applications efficiently.',
    'license': 'OPL-1',
    'category': 'Kawiil/Custom Modules',
    'author': 'alfogtz',
    'website': 'https://github.com/alfogtz/kawiilmotors',
    'version': '18.0.0.0.1',
    'depends': ['base'],
    'data': ['views/loan_application_views.xml',
             'views/motorcycle_financing_menu.xml',],
    'demo': ['data/loan_demo.xml',],
    'application': True,
}
